### ISSUE TITLE
[BUG] NPID++ checkpoint link broken.

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/vissl#516]
## Instructions To Reproduce the 🐛 Bug:

Click on the [link from MODEL ZOO for NPID++](https://dl.fbaipublicfiles.com/vissl/model_zoo/npid_4node_800ep_32kneg_cosine_npid++_4nodes_resnet_23_07_20.75432662/model_final_checkpoint_phase799.torch)

Output:
<img width="815" alt="Screenshot 2022-02-09 at 20 10 08" src="https://user-images.githubusercontent.com/24327668/153335799-c6a2fd99-8ae4-4b0a-bdff-c8680dfbcf99.png">

Is the access restricted to FB employees?

**Comment by YannDubs** [comment]
Thanks @QuentinDuval, it works!

**Comment by QuentinDuval** [comment]
Excellent ! I will send a quick PR to fix this then :)

**Comment by QuentinDuval** [comment]
Fix committed fecffa819f6cc2f213dc8c045eea6a4a6c8d3591

**Comment by YannDubs** [comment]
@QuentinDuval the link for rn50w2 is also broken

**Comment by YannDubs** [comment]
@QuentinDuval the link for rn50w2 is still broken, I think the issue should be reopened.
